"""Faceprompt prompt catalog package."""

from .catalog import (
    BASE_IDENTITY_PROMPT,
    BASE_NEGATIVE_PROMPT,
    HAIRSTYLE_ONLY_IDENTITY_PROMPT,
    PromptAssembly,
    PromptBlock,
    PromptRule,
    SCENE_ONLY_IDENTITY_PROMPT,
    build_prompt_assembly,
    catalog_summary,
    get_prompt_block_labels,
    get_prompt_rule_table,
    get_record,
    list_records,
    recommend_pairings,
    render_hairstyle_only_prompt,
    render_prompt,
    render_scene_only_prompt,
    validate_catalog,
)

__all__ = [
    "BASE_IDENTITY_PROMPT",
    "BASE_NEGATIVE_PROMPT",
    "HAIRSTYLE_ONLY_IDENTITY_PROMPT",
    "PromptAssembly",
    "PromptBlock",
    "PromptRule",
    "SCENE_ONLY_IDENTITY_PROMPT",
    "build_prompt_assembly",
    "catalog_summary",
    "get_prompt_block_labels",
    "get_prompt_rule_table",
    "get_record",
    "list_records",
    "recommend_pairings",
    "render_hairstyle_only_prompt",
    "render_prompt",
    "render_scene_only_prompt",
    "validate_catalog",
]
